# Generated by Django 4.2.8 on 2024-04-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0005_alter_filemodel_options_filemodel_new_id'),
        ('main_page', '0010_alter_newsmodel_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-post_at'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ['name'], 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнери'},
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel'),
        ),
    ]
