# Generated by Django 4.2.8 on 2024-04-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_is_aproved_usermini_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermini',
            options={'verbose_name': 'User Mini', 'verbose_name_plural': 'Users Mini'},
        ),
    ]
