# Generated by Django 4.2.8 on 2024-04-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0005_alter_filemodel_options_filemodel_new_id'),
        ('dog_card', '0009_alter_dogcardmodel_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogcardmodel',
            options={'ordering': ['id'], 'verbose_name': 'Картка собаки', 'verbose_name_plural': 'Картки собак'},
        ),
        migrations.AlterField(
            model_name='dogcardmodel',
            name='photo',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category', 'image')), null=True, on_delete=django.db.models.deletion.CASCADE, to='backblaze.filemodel'),
        ),
    ]
