# Generated by Django 4.2.8 on 2024-04-10 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'Про нас', 'verbose_name_plural': 'Про нас'},
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='quantity_of_animals',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='quantity_of_employees',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='quantity_of_succeeds_adoptions',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
