# Generated by Django 4.2.8 on 2024-04-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0004_alter_filemodel_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AddField(
            model_name='filemodel',
            name='new_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
