# Generated by Django 4.2.8 on 2024-04-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backblaze', '0005_alter_filemodel_options_filemodel_new_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='new_id',
        ),
    ]
